// Shared by AddSkillModal and the onboarding wizard so the two skill inputs
// never drift apart.
export const skillSuggestions = [
  "React Development",
  "JavaScript",
  "TypeScript",
  "Node.js",
  "Python",
  "Machine Learning",
  "Data Science",
  "UI/UX Design",
  "Graphic Design",
  "Digital Marketing",
  "Social Media Marketing",
  "Content Writing",
  "SEO",
  "AWS",
  "DevOps",
  "Docker",
  "Kubernetes",
  "MongoDB",
  "PostgreSQL",
  "Java",
  "C++",
  "Go",
  "Rust",
  "Swift",
  "iOS Development",
  "Android Development",
  "Flutter",
  "React Native",
  "Vue.js",
  "Angular",
  "PHP",
  "Laravel",
  "Django",
  "FastAPI",
  "GraphQL",
  "REST API",
  "Blockchain",
  "Web3",
  "Solidity",
  "Cybersecurity",
  "Network Security",
  "Cloud Computing",
  "Azure",
  "Google Cloud",
  "Linux",
  "Git",
  "Agile",
  "Scrum",
  "Project Management",
  "Product Management",
];

export default skillSuggestions;
